---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: saurabh
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "saurabhv09/calculator_python"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Stop and remove existing container if present and running
      shell: docker stop calculator_python && docker rm calculator_python
      ignore_errors: true
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator_python saurabhv09/calculator_python
